target 'RACAutoDisposer', :exclusive => true do
  pod "RACAutoDisposer", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "RACAutoDisposer", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
